sudo: required
dist: trusty

language: java
jdk: oraclejdk8

cache:
  directories:
  - $HOME/.m2
  - $HOME/.p2
  - extensions/ui/org.eclipse.smarthome.ui.paper/npm_cache

before_install: echo "MAVEN_OPTS='-Xms1g -Xmx2g -XX:PermSize=512m -XX:MaxPermSize=1g'" > ~/.mavenrc

#$ mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
#$ mvn test -B

install:
  - echo 'mvn clean verify -B -V -Dspotbugs.skip=true 1> .build.stdout 2> .build.stderr' > .build.sh
  - chmod 0755 .build.sh
script:
  - travis_wait 60 ./.build.sh
after_success:
  - tail -n  200 .build.stdout
after_failure:
  - tail -n  300 .build.stderr
  - tail -n 2000 .build.stdout
